DEFAULT_FONT_NAME = 'Arial'
HEADER_FONT_SIZE = 24
DEFAULT_FONT_SIZE = 12

DEFAULT_ENTRY_WIDTH = 10
DEFAULT_ENTRY_PAD = (0, 10)

HEADER_FONT = (DEFAULT_FONT_NAME, HEADER_FONT_SIZE)
DEFAULT_FONT = (DEFAULT_FONT_NAME, DEFAULT_FONT_SIZE)
LABEL_FONT = (DEFAULT_FONT_NAME, DEFAULT_FONT_SIZE, 'bold')

DEFAULT_FRAME_BORDER = 2

################

DEFAULT_SPEED = 0.5
DEFAULT_ACCELERATION = 0.5

DEFAULT_GRIPPER_SPEED = 10
DEFAULT_GRIPPER_FORCE = 10

################

URI1_HOST = "192.168.56.101"
URI2_HOST = "192.168.57.101"

"""
import sim_uri
URI1_HOST = "192.168.56.101"
URI2_HOST = "192.168.57.101"
ayal = sim_uri.RMPLAB_Uri(URI2_HOST)
uri = sim_uri.RMPLAB_Uri(URI1_HOST)
ayal.connect(False)
uri.connect(False)
"""