from .panel_header import *
from .panel_connection import *
from .panel_main_navigation import *
from .panel_actual_tcp import *
from .panel_actual_q import *
from .panel_gripper import *
from .panel_calibrate import *
from .panel_move_to import *
from .panel_move_tcp import *
from .panel_move_both_tcp import *
from .panel_loop_move import *
from .panel_tcp_force import *
from .panel_explore_force import *
from .panel_pnp import *
from .panel_alpha_puzzle import *
from .panel_sim_visibility import *
from .panel_sim_camera import *
from .panel_sim_settings import *
